version = 0.1

[default.global.parameters]
stack_name = "pa-agent"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "ap-southeast-2"
parameter_overrides = "Environment=prod"
fail_on_empty_changeset = false
